{% set version = "0.1.4" %}

package:
  name: adnus
  version: {{ version }}

source:
  path: .  # Yerel kaynak kodunun dizinini belirtin
  url: https://files.pythonhosted.org/packages/9f/c1/a6bde10a4aff913cd9164de869afdcc07092cfb7b4026f5e11bc4d5bd932/adnus-0.1.3.tar.gz
  sha256: d236b9c36a009f052e7148e1d2185cf27275f7b45871124d1c0a91c3282aefeb

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: python -m pip install --ignore-installed .  # Kurulum komutu
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
  run:
    - python

about:
  home: https://github.com/WhiteSymmetry/adnus
  license: MIT
  summary: 'adnus (AdNuS):  Advanced Number Systems.'
  description: |
    adnus (AdNuS):  Advanced Number Systems.
  dev_url: https://github.com/WhiteSymmetry/adnus
  doc_url: https://github.com/WhiteSymmetry/adnus
  doc_source_url: https://github.com/WhiteSymmetry/adnus/blob/main/README.md
  
